name: Deploy Entract

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install

    - name: Build and deploy
      run: |
        npm run build

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./
